"""
Network Inference Script

This script uses the netinf executable to infer networks from cascade data.
It creates multiple networks using different alpha values based on a log-scale grid
derived from the median time differences in the cascades.

Parameters:
- cascades_file: Path to cascades file (generated by generate_cascades.py)
- N: Number of different alpha values to generate (log-spaced grid)
- model: Model type (0:exponential, 1:powerlaw, 2:rayleigh)
- max_iter: Maximum number of iterations for the inference algorithm
- name_output: Base name for output files
- r: Multiplicative range factor for alpha grid (default: 100)

The alpha values are automatically computed from the median time differences (Δ) 
in the cascades using appropriate models:
- Exponential model: α = ln(2)/Δ 
- Rayleigh model: α = 2*ln(2)/Δ²

The inferred networks are stored in data/inferred_networks/ with subfolders for each model.
"""

import os
import glob
import shutil
import subprocess
import numpy as np
import pandas as pd
from calculate_delta import compute_median_delta, alpha_centers_from_delta, log_alpha_grid

def create_output_directories(base_path, model_name):
    """
    Create necessary output directories.
    
    Args:
        base_path (str): Base path for inferred networks
        model_name (str): Name of the model (exponential, powerlaw, rayleigh)
    
    Returns:
        tuple: (model_directory_path, edge_info_directory_path)
    """
    model_dir = os.path.join(base_path, model_name)
    edge_info_dir = os.path.join(model_dir, 'edge_info')
    os.makedirs(model_dir, exist_ok=True)
    os.makedirs(edge_info_dir, exist_ok=True)
    return model_dir, edge_info_dir

def cleanup_edge_info_files(model_suffix, edge_info_dir):
    """
    Clean up any remaining edge info files that might not have been moved during processing.
    
    Args:
        model_suffix (str): Model suffix (expo, power, ray)
        edge_info_dir (str): Path to the edge info directory
    """
    try:
        # Look for any remaining edge info files in the current directory
        pattern = f"*-{model_suffix}-*-edge.info"
        remaining_files = glob.glob(pattern)
        moved_count = 0
        for file_path in remaining_files:
            try:
                destination = os.path.join(edge_info_dir, os.path.basename(file_path))
                shutil.move(file_path, destination)
                moved_count += 1
            except Exception as e: # pylint: disable=broad-except
                print(f"  Warning: Could not move {file_path}: {str(e)}")

        if moved_count > 0:
            print(f"  Cleanup: Moved {moved_count} remaining edge info files")

    except Exception as e: # pylint: disable=broad-except
        print(f"  Warning: Error during edge info cleanup: {str(e)}")

def infer_networks(
        cascades_file="cascades.txt",
        n=100,
        model=0,
        max_iter=2000,
        name_output="inferred-network",
        r=100.0
    ):
    """
    Infer networks using the netinf executable with log-spaced alpha values derived from cascade data.
    
    Args:
        cascades_file (str): Name of the cascades file in the data folder (default: "cascades.txt")
        n (int): Number of different alpha values to generate (default: 100)
        model (int): Model type - 0:exponential, 1:powerlaw, 2:rayleigh (default: 0)
        max_iter (int): Maximum number of iterations (default: 2000)
        name_output (str): Base name for output files (default: "inferred-network")
        r (float): Multiplicative range factor for alpha grid (default: 100.0)
    
    Returns:
        bool: True if successful, False otherwise
    """
    # Model names mapping
    model_names = {0: "exponential", 1: "powerlaw", 2: "rayleigh"}
    model_short = {0: "expo", 1: "power", 2: "ray"}

    if model not in model_names:
        print(f"Error: Invalid model {model}. Must be 0, 1, or 2.")
        return False

    model_name = model_names[model]
    model_suffix = model_short[model]

    try:
        # Check if cascades file exists
        cascades_path = os.path.join('..', 'data', cascades_file)
        if not os.path.exists(cascades_path):
            print(f"Error: Cascades file '{cascades_path}' not found.")
            print("Please run generate_cascades.py first to create the cascades file.")
            return False

        # Compute median delta from cascades
        print("Computing median time differences (Δ) from cascades...")
        delta_seconds = compute_median_delta(cascades_file)

        if delta_seconds is None:
            print("Error: Could not compute median delta from cascades.")
            return False

        print(f"Median Δ = {delta_seconds:.2f} seconds ({delta_seconds/86400:.2f} days)")

        # Compute alpha centers for the specific model
        alpha_centers = alpha_centers_from_delta(delta_seconds)
        alpha_center = None
        alpha_values = None

        # Select the appropriate alpha center based on model and generate alpha grid
        if model == 0:  # Exponential
            alpha_center = alpha_centers["exp_per_sec"]
            alpha_values = log_alpha_grid(alpha_center, r=r, N=n)
            print(f"Using exponential model: α_center = {alpha_center:.6e} per second")
        elif model == 1:  # Powerlaw
            # alpha is dimensionless, so use a linear scale
            alpha_values = np.linspace(1, 5, n)
        elif model == 2:  # Rayleigh
            alpha_center = alpha_centers["ray_per_sec2"]
            alpha_values = log_alpha_grid(alpha_center, r=r, N=n)
            print(f"Using Rayleigh model: α_center = {alpha_center:.6e} per second²")

        alpha_min, alpha_max = alpha_values.min(), alpha_values.max()
        print(f"Generated log-spaced alpha grid: [{alpha_min:.2e}, {alpha_max:.2e}] with {n} points")

        # Create output directories
        base_output_dir = os.path.join('..', 'data', 'inferred_networks')
        model_output_dir, edge_info_dir = create_output_directories(base_output_dir, model_name)

        print(f"Starting network inference with {n} alpha values...")
        print(f"Model: {model_name} ({model})")
        print(f"Alpha range: {alpha_min:.2e} to {alpha_max:.2e} (log-spaced)")
        print(f"Max iterations: {max_iter}")
        print(f"Output directory: {model_output_dir}")

        edges_count = []
        successful_inferences = 0

        # Check if netinf executable exists
        if not os.path.exists('./netinf'):
            print("Error: netinf executable not found in current directory.")
            print("Please make sure the netinf executable is compiled and available.")
            return False

        for i, alpha in enumerate(alpha_values):
            try:
                print(f"Processing network {i+1}/{n} with alpha={alpha:.2e}")

                # Create output filename
                output_filename = f"{name_output}-{model_suffix}-{i:03d}"

                # Execute netinf algorithm
                command = [
                    "./netinf",
                    f"-i:{cascades_path}",
                    f"-o:{output_filename}",
                    f"-m:{model}",
                    f"-e:{max_iter}",
                    f"-a:{alpha}"
                ]

                # Run the command
                result = subprocess.run(
                    command,
                    capture_output=True,
                    text=True,
                    cwd='.',
                    check=False
                )

                if result.returncode != 0:
                    print(f"Warning: netinf failed for alpha {alpha:.2e}")
                    print(f"Error output: {result.stderr}")
                    edges_count.append(0)
                    continue

                # Check if output file was created
                output_file = f"{output_filename}.txt"
                if not os.path.exists(output_file):
                    print(f"Warning: Output file {output_file} not created for alpha {alpha:.2e}")
                    edges_count.append(0)
                    continue

                # Count edges in the inferred network
                try:
                    with open(output_file, 'r', encoding='utf-8') as fp:
                        lines = fp.readlines()
                        # Skip the first block (nodes) and count edges in second block
                        in_edges_section = False
                        edge_count = 0
                        for line in lines:
                            line = line.strip()
                            if not line:  # Empty line separates blocks
                                in_edges_section = True
                                continue
                            if in_edges_section:
                                edge_count += 1

                        edges_count.append(edge_count)

                except Exception as e: # pylint: disable=broad-except
                    print(f"Warning: Could not count edges in {output_file}: {str(e)}")
                    edges_count.append(0)

                # Move inferred network to model-specific folder
                destination = os.path.join(model_output_dir, output_file)
                shutil.move(output_file, destination)

                # Check for and move edge info file if it exists
                edge_info_file = f"{output_filename}-edge.info"
                if os.path.exists(edge_info_file):
                    edge_info_destination = os.path.join(edge_info_dir, edge_info_file)
                    shutil.move(edge_info_file, edge_info_destination)

                successful_inferences += 1

            except Exception as e: # pylint: disable=broad-except
                print(f"Error processing alpha {alpha:.2e}: {str(e)}")
                edges_count.append(0)

        # Save the results
        results_df = pd.DataFrame({
            'alpha': alpha_values,
            f'inferred_edges_{model_suffix}': edges_count
        })

        results_file = os.path.join(model_output_dir, f'inferred_edges_{model_suffix}.csv')
        results_df.to_csv(results_file, sep='|', index=False)

        # Also save alpha grid information
        alpha_info_df = pd.DataFrame({
            'median_delta_seconds': [delta_seconds],
            'alpha_center': [alpha_center],
            'alpha_min': [alpha_min],
            'alpha_max': [alpha_max],
            'r_factor': [r],
            'model_type': [model_name]
        })

        alpha_info_file = os.path.join(model_output_dir, f'alpha_grid_info_{model_suffix}.csv')
        alpha_info_df.to_csv(alpha_info_file, index=False)

        # Clean up any remaining edge info files
        cleanup_edge_info_files(model_suffix, edge_info_dir)

        print("\nInference completed!")
        print(f"Successful inferences: {successful_inferences}/{n}")
        print(f"Results saved to: {results_file}")
        print(f"Alpha grid info saved to: {alpha_info_file}")
        print(f"Network files saved to: {model_output_dir}")
        print(f"Edge info files saved to: {edge_info_dir}")

        return True

    except Exception as e: # pylint: disable=broad-except
        print(f"Error during network inference: {str(e)}")
        return False

def infer_networks_all_models(
        cascades_file="cascades.txt",
        n=100,
        max_iter=2000,
        name_output="inferred-network",
        r=100.0):
    """
    Infer networks for all three models (exponential, powerlaw, rayleigh) using log-spaced alpha grids.
    
    Args:
        cascades_file (str): Name of the cascades file in the data folder
        n (int): Number of different alpha values to generate
        max_iter (int): Maximum number of iterations
        name_output (str): Base name for output files
        r (float): Multiplicative range factor for alpha grid
    
    Returns:
        dict: Results for each model
    """
    results = {}
    models = {0: "exponential", 1: "powerlaw", 2: "rayleigh"}

    for model_id, model_name in models.items():
        print(f"\n{'='*60}")
        print(f"Starting inference for {model_name.upper()} model")
        print(f"{'='*60}")

        success_netinf = infer_networks(
            cascades_file=cascades_file,
            n=n,
            model=model_id,
            max_iter=max_iter,
            name_output=name_output,
            r=r
        )

        results[model_name] = success_netinf

    print(f"\n{'='*60}")
    print("ALL MODELS INFERENCE SUMMARY")
    print(f"{'='*60}")
    for model_name, success_val in results.items():
        status = "SUCCESS" if success_val else "FAILED"
        print(f"{model_name.capitalize()}: {status}")

    return results
